//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationDBContextContainer : DbContext
    {
        public ApplicationDBContextContainer()
            : base("name=ApplicationDBContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> PersonaSet { get; set; }
        public virtual DbSet<Especialidad> EspecialidadSet { get; set; }
        public virtual DbSet<Turno> TurnoSet { get; set; }
        public virtual DbSet<Consulta> ConsultaSet { get; set; }
        public virtual DbSet<HistoriaClinica> HistoriaClinicaSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Permiso> PermisoSet { get; set; }
    }
}
