//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente : Persona
    {
        public int HistoriaClinicaId { get; set; }
        public string ObraSocial { get; set; }
        public int NumeroAfiliado { get; set; }
    
        public virtual HistoriaClinica HistoriaClinica1 { get; set; }
    }
}
